// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noskvkbffpezmwsstjzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vc2t2a2JmZnBlem13c3N0anpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE1MzksImV4cCI6MjA2NTQ5NzUzOX0.8zrVS16slPqvxRbrpfsE0wuS0bsCIGkpK2fB_MRwTUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);